### ISSUE TITLE
SteamMatchmaking ?

### ISSUE THREAD

**Issue by kevinmurphy678** [code-disaster/steamworks4j#20]
Is this implemented yet? I'd like to create lobbies and be able to use matchmaking features in my game at some point. The features are here: https://partner.steamgames.com/documentation/matchmaking

How hard would it be to add in these to the wrapper?

**Comment by code-disaster** [comment]
Matchmaking isn't implemented yet. Adding wrappers won't be "hard" as far as I can tell, it'll just be quite some work because of the numerous interfaces and functions involved.

**Comment by kevinmurphy678** [comment]
All I really need is the ability to join and create lobbies, and maybe the
master server functions. I could probably figure it out myself if you don't
have the time to implement it. There's no rush as I won't be needing it for
a while

**Comment by code-disaster** [comment]
I started working on that in a separate branch. You may follow progress if you are interested.

> and maybe the master server functions.

What functions exactly do you talk about?

**Comment by kevinmurphy678** [comment]
Nevermind about the master server, it seems lobbies will be able to do everything I need.
Thanks for doing this!

**Comment by code-disaster** [comment]
Merged the branch back to master. Most lobby functions are implemented, partially tried by the new test app. Let me know how things work out for you.

**Comment by kevinmurphy678** [comment]
Thanks! I'll take a look at it and let you know how it works out

**Comment by kevinmurphy678** [comment]
I'm getting an error when trying to get lobby data(in the test app and my own game).
```java
Initialise Steam client API ...
Persona state changed (unhandled): accountID=39359953, change=GamePlayed
lobby create 2
  creating lobby for 2 players.
Lobby created: 18600005ae56e94
  - result: OK
Lobby data update for 18600005ae56e94
  - member: 1524985492
  - success: true
Lobby data update for 18600005ae56e94
  - member: 1524985492
  - success: true
Persona state changed (unhandled): accountID=39359953, change=GameServer
lobby data 18600005ae56e94
Exception in thread "Thread-0" java.lang.UnsatisfiedLinkError: com.codedisaster.steamworks.SteamMatchmaking.getLobbyDataCount(JJ)I
	at com.codedisaster.steamworks.SteamMatchmaking.getLobbyDataCount(Native Method)
	at com.codedisaster.steamworks.SteamMatchmaking.getLobbyDataCount(SteamMatchmaking.java:212)
	at com.codedisaster.steamworks.test.SteamMatchmakingTestApp.processInput(SteamMatchmakingTestApp.java:224)
	at com.codedisaster.steamworks.test.SteamTestApp$InputHandler.run(SteamTestApp.java:42)
	at java.lang.Thread.run(Thread.java:745)
```
The same error happens with "matchmaking.getLobbyDataByIndex"

maybe my libraries aren't up to date. I'll try rebuilding them and see what happens

**Comment by kevinmurphy678** [comment]
I'm trying to run the jnigen generator but can't seem to get it to generate properly. 
```java
Generating C/C++ for 'src\main\java\com\codedisaster\steamworks\SteamAPI.java'...
Command: javah -classpath target/classes -o src/main/native/com.codedisaster.steamworks.SteamAPI.h com.codedisaster.steamworks.SteamAPI
Error: Could not find class file for 'com.codedisaster.steamworks.SteamAPI'.
java.lang.RuntimeException: Error reading file: src\main\native\com.codedisaster.steamworks.SteamAPI.h (Absolute)
	at com.badlogic.gdx.jnigen.FileDescriptor.read(FileDescriptor.java:127)
	at com.badlogic.gdx.jnigen.FileDescriptor.readString(FileDescriptor.java:176)
	at com.badlogic.gdx.jnigen.FileDescriptor.readString(FileDescriptor.java:166)
	at com.badlogic.gdx.jnigen.NativeCodeGenerator.generateCppFile(NativeCodeGenerator.java:303)
	at com.badlogic.gdx.jnigen.NativeCodeGenerator.processDirectory(NativeCodeGenerator.java:267)
	at com.badlogic.gdx.jnigen.NativeCodeGenerator.processDirectory(NativeCodeGenerator.java:245)
	at com.badlogic.gdx.jnigen.NativeCodeGenerator.processDirectory(NativeCodeGenerator.java:245)
	at com.badlogic.gdx.jnigen.NativeCodeGenerator.processDirectory(NativeCodeGenerator.java:245)
	at com.badlogic.gdx.jnigen.NativeCodeGenerator.generate(NativeCodeGenerator.java:236)
	at com.codedisaster.steamworks.jnigen.JNICodeGenerator.main(JNICodeGenerator.java:10)
Caused by: java.io.FileNotFoundException: src\main\native\com.codedisaster.steamworks.SteamAPI.h (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.badlogic.gdx.jnigen.FileDescriptor.read(FileDescriptor.java:123)
	... 9 more
```

Any chance you could update the libraries? If that's the issue with the lobby data error

**Comment by code-disaster** [comment]
Hm, not sure what I did wrong, because I'm pretty certain I've tried these functions before. :) Anyway, I've updated the libraries again, and upgraded to SDK v1.35 too.

For the code generator you need to ensure that the working directory is set to steamworks4j/java-wrapper/, and that the Java code has been compiled. Jnigen does some arcane stuff which needs to access both the source code and the compiled class.

**Comment by kevinmurphy678** [comment]
The updated binaries fixed it. Everything seems to be working now
Here's a quick video test from my game http://files.catbox.moe/0760da.mp4

**Comment by code-disaster** [comment]
Nice. Just out of curiosity, do you use SteamNetworking or some other library?

**Comment by kevinmurphy678** [comment]
I use kryonet for networking. Steam lobbies just send the ip and port to
join through lobby data when connecting to them. You still need ports
forwarded to host games but I can't really fix that without rewriting
everything.

I still have to get my game on steam(using spacewar appid). Adding steam
invites was just an experiment to see how it works with kryonet or another
library
