### ISSUE TITLE
Steam Matchmaking UnsatisfiedLink on startup

### ISSUE THREAD

**Issue by Quexten** [code-disaster/steamworks4j#21]
I tried the SteamMatchmakingTestApp from the matchmaking branch. After staring it gave me:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: com.codedisaster.steamworks.SteamAPI.getSteamMatchmakingPointer()J
	at com.codedisaster.steamworks.SteamAPI.getSteamMatchmakingPointer(Native Method)
	at com.codedisaster.steamworks.SteamMatchmaking.<init>(SteamMatchmaking.java:136)
	at com.codedisaster.steamworks.test.SteamMatchmakingTestApp.registerInterfaces(SteamMatchmakingTestApp.java:153)
	at com.codedisaster.steamworks.test.SteamTestApp.runAsClient(SteamTestApp.java:75)
	at com.codedisaster.steamworks.test.SteamTestApp.clientMain(SteamTestApp.java:111)
	at com.codedisaster.steamworks.test.SteamMatchmakingTestApp.main(SteamMatchmakingTestApp.java:255)
```
Any suggestions on how to get it to work?

**Comment by code-disaster** [comment]
This happens because the prebuilt native libraries are not up-to-date. Usually I try to avoid updating prebuilt libraries in feature branches.

**Comment by code-disaster** [comment]
The matchmaking branch is now merged back to master, including updated native libraries.

**Comment by Quexten** [comment]
Yup, works after replacing the natives, thanks!
