### ISSUE TITLE
Bug: Running 2+ Steam Apps /w Steamworks4J (steam_api.dll cannot be accessed)

### ISSUE THREAD

**Issue by noblemaster** [code-disaster/steamworks4j#40]
Running more than one app using Steamworks4J will result in an **error accessing the steam_api.dll for the second app**. Please note those apps run independently on different JVMs. This is the error that the 2nd app will receive:

> steam_api.dll (The process cannot access the file because it is being used by another process)

It appears the first app locks access to the steam_api.dll preventing the 2nd app from using it/initializing Steam! Could that DLL be simply placed in a separate temp directory to make it all work again?

Stacktrace:
```
com.codedisaster.steamworks.SteamException: java.io.FileNotFoundException: C:\Users\CHRIST~1\AppData\Local\Temp\steamworks4j\ec05efa3\steam_api.dll (The process cannot access the file because it is being used by another process)
	at SteamSharedLibraryLoader.loadLibraries(SteamSharedLibraryLoader.java:163)
	at com.codedisaster.steamworks.SteamAPI.init(SteamAPI.java:15)
	at com.codedisaster.steamworks.SteamAPI.init(SteamAPI.java:10)
	at com.noblemaster.lib.boot.plaf.impl.commondesk.arch.t.a(SourceFile:91)
	at com.noblemaster.lib.boot.plaf.impl.commondesk.arch.p.a(SourceFile:199)
	at com.noblemaster.lib.gear.b.b.b.i.c(SourceFile:140)
	at com.noblemaster.lib.boot.a.m.n(SourceFile:145)
	at com.noblemaster.lib.boot.a.l.i(SourceFile:37)
	at com.noblemaster.lib.boot.a.m.i(SourceFile:177)
	at com.noblemaster.lib.boot.plaf.impl.b.g.create(SourceFile:623)
	at com.noblemaster.lib.boot.plaf.impl.b.ae.create(SourceFile:400)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:147)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
Caused by: java.io.FileNotFoundException: C:\Users\CHRIST~1\AppData\Local\Temp\steamworks4j\ec05efa3\steam_api.dll (The process cannot access the file because it is being used by another process)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at  SteamSharedLibraryLoader.extractLibrary(SteamSharedLibraryLoader.java:115)
	at  SteamSharedLibraryLoader.loadLibraries(SteamSharedLibraryLoader.java:83)
	at  SteamSharedLibraryLoader.loadLibraries(SteamSharedLibraryLoader.java:161)
	... 12 more

```

**Comment by code-disaster** [comment]
Out of curiosity, what's your use case?

**Comment by noblemaster** [comment]
It's rather rare: I had a few players reporting not being able to login (via Steam) to one of the games. It's 2 turn-based games where players might open the another game while waiting for new turns for the old game. The second time the open a game, login via Steam (given Steam was unable to initialize) won't work. Also, if a game doesn't properly shutdown (could be any other game that uses Steamworks4J), will prevent any new game for accessing Steam.

Also, I have some moderators that moderate in 2 games and keep two of the apps open. Steam simply won't initialize for the second game.
