### ISSUE TITLE
Windows Library could not be loaded

### ISSUE THREAD

**Issue by AlrikG** [code-disaster/steamworks4j#49]
Hi,
since the last few changes, the server could not be loaded anymore. I get the following error in my client/server test case (the missing DLL exists in steamworks4j-server-1.7.0-SNAPSHOT.jar):

```
  Steam API initialized: true
  Steam client active: true
  Steam API initialized: true
  Steam client active: true
java.lang.UnsatisfiedLinkError: C:\Users\Alrik\AppData\Local\Temp\steamworks4j\1.7.0-SNAPSHOT\steamworks4j-server64.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.codedisaster.steamworks.SteamSharedLibraryLoader.loadLibrary(SteamSharedLibraryLoader.java:122)
	at com.codedisaster.steamworks.SteamGameServerAPI.init(SteamGameServerAPI.java:32)
	at com.codedisaster.steamworks.SteamGameServerAPI.init(SteamGameServerAPI.java:17)
	at net.qb.steamworks.SteamworksStateServer.<init>(SteamworksStateServer.java:54)
	at net.qb.steamworks.SteamworkTest.main(SteamworkTest.java:53)
java.lang.UnsatisfiedLinkError: com.codedisaster.steamworks.SteamGameServerAPINative.getSteamGameServerPointer()J
	at com.codedisaster.steamworks.SteamGameServerAPINative.getSteamGameServerPointer(Native Method)
	at com.codedisaster.steamworks.SteamGameServer.<init>(SteamGameServer.java:33)
	at net.qb.steamworks.SteamworksStateServer.initialize(SteamworksStateServer.java:97)
	at com.jme3.app.state.AppStateManager.initializePending(AppStateManager.java:251)
	at com.jme3.app.state.AppStateManager.update(AppStateManager.java:281)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:236)
	at net.qb.steamworks.SteamworkTest.initSteamworks(SteamworkTest.java:70)
	at net.qb.steamworks.SteamworkTest.simpleInitApp(SteamworkTest.java:268)
	at com.jme3.app.SimpleApplication.initialize(SimpleApplication.java:220)
	at com.jme3.system.lwjgl.LwjglWindow.initInThread(LwjglWindow.java:500)
	at com.jme3.system.lwjgl.LwjglWindow.run(LwjglWindow.java:600)
	at com.jme3.system.lwjgl.LwjglWindow.create(LwjglWindow.java:445)
	at com.jme3.app.LegacyApplication.start(LegacyApplication.java:463)
	at com.jme3.app.LegacyApplication.start(LegacyApplication.java:424)
	at com.jme3.app.SimpleApplication.start(SimpleApplication.java:125)
	at net.qb.steamworks.SteamworkTest.main(SteamworkTest.java:65)
```

**Comment by AlrikG** [comment]
I have some news about this: I seems that it only works if I copy "sdkencryptedappticket64.dll" directly into my project folder. This file is NOT extracted into the temp folder "C:\Users\Alrik\AppData\Local\Temp\steamworks4j\1.7.0-SNAPSHOT"

**Comment by code-disaster** [comment]
In the latest version, the encrypted app ticket functions are now compiled to a separate library, so sdkencryptedappticket64.dll is not required anymore to use SteamGameServerAPI.
